- name: configuring frontend
  hosts: frontend.ganeshsiripuram.tech
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: starting the nginx
    ansible.builtin.service:
      name: nginx
      state: started

  - name: remove the default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: downloading the content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip


  - name: changing the directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: copying the content
    ansible.builtin.copy:
      src: /tmp/frontend.zip
      dest: /etc/nginx/default.d/expense.conf

  - name: start the service
    ansible.builtin.service:
      name: nginx
      state: restarted
